### PR TITLE
Spike: redis-on-nodejs

### PR DESCRIPTION
**Pull request by blazejkrzak**
Redis implementation to notification service

### CODE REVIEW

**Comment by radzom** [comment]
Hi, my name is Gunnar I am working as a senior engineer for adorsys. Francis wanted me to review this. 

Since there is no Issue linked with the pull request I kind of had to guess what the Task was. After checking back with Jan and Francis it seems like there have been misunderstandings in the communication of what should have been done and what was finally done.

Reviewing the pull request I see two new api endpoints for writing and reading values to and from redis. Please correct me if I am wrong on this. That was not the feature needed by adorsys.

I will try to describe the feature that adorsys wants. But I will do it  here https://github.com/adorsys/notification-service/issues/4 to help some future reviewer (likely it will be my future me).

**Comment by radzom** [comment]
And of course I invite both adorsys and binarapps to comment and to refine the new Issue #4 .

**Comment by blazejkrzak** [comment]
I do not agree fully. Last piece missing is to write middleware that handles each endpoint.

**Comment by blazejkrzak** [comment]
These two endpoints put/get was added only for Adorsys to allow you to check if redis is connected properly

**Comment by blazejkrzak** [comment]
But I totally agree with issues and proper descriptions. It allows us to ommit communication gaps :)

**Pull request closed without merging**
